### ISSUE TITLE
Exception thrown in server

### ISSUE THREAD

**Issue by skelfu** [Shadows-of-Fire/ClickMachine#13]
after I place a clickmechine it throw some exceptions 

[20:58:35] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.NetHandlerPlayServer.<init>(NetHandlerPlayServer.java:236) ~[pa.class:?]
	at shadows.click.util.NetHandlerSpaghettiServer.<init>(NetHandlerSpaghettiServer.java:46) ~[NetHandlerSpaghettiServer.class:?]
	at shadows.click.util.FakePlayerUtil.lambda$getPlayer$0(FakePlayerUtil.java:78) ~[FakePlayerUtil.class:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_231]
	at shadows.click.util.FakePlayerUtil.getPlayer(FakePlayerUtil.java:76) ~[FakePlayerUtil.class:?]
	at shadows.click.block.TileAutoClick.func_73660_a(TileAutoClick.java:52) ~[TileAutoClick.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2170) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:745) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:909) ~[MinecraftServer.class:?]
	... 4 more
[20:58:35] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: F:\新建文件夹 (2)\CatServer 1.12.2\.\crash-reports\crash-2020-02-02_20.58.35-server.txt
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[20:58:35] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: skelfu lost connection: Server closed
[20:58:35] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: skelfu left the game
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'DIM-1'/the_nether
[20:58:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'DIM1'/the_end
[20:58:35] [Server thread/INFO] [FML]: Unloading dimension 0
[20:58:35] [Server thread/INFO] [FML]: Unloading dimension -1
[20:58:35] [Server thread/INFO] [FML]: Unloading dimension 1
[20:58:35] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by Shadows-of-Fire** [comment]
1.12.2 is not supported

**Comment by zediious** [comment]
> 
> 
> 1.12.2 is not supported

Am I to take from this you won't provide any support for this mod on a 1.12.2 platform?
